print('January\nFebruary\nmarch\nApril\nMay\nJune\nJuly\nAugust\nSeptember\nOctober\nNovember\nDecember')
print("{},{},{},{},{},{},{}".format("Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"))
print("""1
2
3
4
5
6
7
8
9
10""")